apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: dockercoins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: salah0250/devops:web
          ports:
            - containerPort: 80