name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push db image
      uses: docker/build-push-action@v2
      with:
        context: ./db
        file: ./db/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/devops:db

    - name: Build and push words image
      uses: docker/build-push-action@v2
      with:
        context: ./words
        file: ./words/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/devops:words

    - name: Build and push web image
      uses: docker/build-push-action@v2
      with:
        context: ./web
        file: ./web/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/devops:web